- hosts: all
  tasks:
    - name: run this command and ignore the result
      shell: "echo running remove exec. I am: $('hostname')"
      ignore_errors: True
      register: hello
    - debug: msg="{{ hello.stdout }}"